- generic [active] [ref=e1]:
  - navigation [ref=e2]:
    - generic [ref=e3]:
      - link "Winning Adventure Global" [ref=e4] [cursor=pointer]:
        - /url: /
        - img "Winning Adventure Global" [ref=e5]
      - list [ref=e6]:
        - listitem [ref=e7]:
          - link "Home" [ref=e8] [cursor=pointer]:
            - /url: /
        - listitem [ref=e9]:
          - link "Services" [ref=e10] [cursor=pointer]:
            - /url: /services
        - listitem [ref=e11]:
          - link "Resources" [ref=e12] [cursor=pointer]:
            - /url: /resources
        - listitem [ref=e13]:
          - link "About Us" [ref=e14] [cursor=pointer]:
            - /url: /about
        - listitem [ref=e15]:
          - link "Enquiry" [ref=e16] [cursor=pointer]:
            - /url: /enquiry
      - generic [ref=e17]:
        - link "Call Us Today +61 0416588198" [ref=e18] [cursor=pointer]:
          - /url: tel:+61416588198
          - generic [ref=e19]: Call Us Today
          - generic [ref=e20]: +61 0416588198
        - link "Start Your Factory Tour →" [ref=e21] [cursor=pointer]:
          - /url: /enquiry
    - generic [ref=e22]:
      - generic [ref=e23]:
        - generic [ref=e24]: Menu
        - button "Close navigation menu" [ref=e25] [cursor=pointer]:
          - img [ref=e26]
      - list [ref=e29]:
        - listitem [ref=e30]:
          - link "Home" [ref=e31] [cursor=pointer]:
            - /url: /
        - listitem [ref=e32]:
          - link "Services" [ref=e33] [cursor=pointer]:
            - /url: /services
        - listitem [ref=e34]:
          - link "Resources" [ref=e35] [cursor=pointer]:
            - /url: /resources
        - listitem [ref=e36]:
          - link "About" [ref=e37] [cursor=pointer]:
            - /url: /about
        - listitem [ref=e38]:
          - link "Enquiry" [ref=e39] [cursor=pointer]:
            - /url: /enquiry
  - generic [ref=e46]:
    - paragraph [ref=e49]: Adelaide · Australia
    - heading "See the factory. Meet your supplier. Cut to the chase — save 20%+ on procurement." [level=1] [ref=e50]:
      - generic [ref=e51]: See the factory.
      - generic [ref=e52]: Meet your supplier.
      - generic [ref=e53]: Cut to the chase
      - generic [ref=e54]: — save 20%+ on procurement.
    - paragraph [ref=e55]: Guided China factory tours for Australian businesses — we coordinate the arrangements, you make the call.
    - generic [ref=e56]:
      - link "Book a Factory Tour" [ref=e57] [cursor=pointer]:
        - /url: /enquiry
        - text: Book a Factory Tour
        - img [ref=e58]
      - link "See How It Works" [ref=e60] [cursor=pointer]:
        - /url: "#howitworks"
        - text: See How It Works
        - img [ref=e61]
    - generic [ref=e63]:
      - generic [ref=e64]:
        - img [ref=e65]
        - generic [ref=e67]: Across 50+ Industries
      - generic [ref=e68]:
        - img [ref=e69]
        - generic [ref=e71]: 500+ Verified Suppliers
      - generic [ref=e72]:
        - img [ref=e73]
        - generic [ref=e75]: 24hr Response Time
  - generic [ref=e77]:
    - generic [ref=e78]:
      - paragraph [ref=e79]: Our Services
      - heading "How Would You Like to Find Your Factory?" [level=2] [ref=e80]
    - generic [ref=e81]:
      - generic [ref=e82]:
        - img [ref=e84]
        - heading "Full Service / Guided Tours" [level=3] [ref=e87]
        - paragraph [ref=e88]: Your dedicated guide handles every detail — from factory matching to on-ground logistics.
        - list [ref=e89]:
          - listitem [ref=e90]:
            - generic [ref=e92]: Dedicated guide accompanies you
          - listitem [ref=e93]:
            - generic [ref=e95]: Factory screening and matching
          - listitem [ref=e96]:
            - generic [ref=e98]: Quality control guidance
          - listitem [ref=e99]:
            - generic [ref=e101]: Contract follow-up support
        - link "See Our Services" [ref=e102] [cursor=pointer]:
          - /url: /services
          - text: See Our Services
          - img [ref=e103]
      - generic [ref=e105]:
        - img [ref=e107]
        - heading "Factory Directory Access — Free" [level=3] [ref=e111]
        - paragraph [ref=e112]: Browse verified manufacturers independently at no cost — submit an enquiry to unlock full contact details.
        - list [ref=e113]:
          - listitem [ref=e114]:
            - generic [ref=e116]: Free access to factory directory
          - listitem [ref=e117]:
            - generic [ref=e119]: Browse partial factory previews
          - listitem [ref=e120]:
            - generic [ref=e122]: Submit enquiry for full details
        - button "Access Directory Free" [ref=e123] [cursor=pointer]:
          - text: Access Directory Free
          - img [ref=e124]
  - generic [ref=e127]:
    - generic [ref=e128]:
      - paragraph [ref=e129]: Our Process
      - heading "Your China Trip, End to End" [level=2] [ref=e130]
      - paragraph [ref=e131]: From pre-trip research to post-trip contracts — we handle every step of your sourcing journey with expertise and care.
    - generic [ref=e132]:
      - generic [ref=e135]:
        - generic [ref=e136]: "1"
        - img [ref=e138]
        - heading "Submit Your Inquiry" [level=3] [ref=e141]
        - paragraph [ref=e142]: Fill out our enquiry form with your industry, product type, and sourcing requirements. We'll get back to you within 24 hours.
      - generic [ref=e144]:
        - generic [ref=e145]: "2"
        - img [ref=e147]
        - heading "We Review & Match" [level=3] [ref=e150]
        - paragraph [ref=e151]: Within 3-7 days, we review your requirements and shortlist 2-3 pre-screened factories from our verified network.
      - generic [ref=e153]:
        - generic [ref=e154]: "3"
        - img [ref=e156]
        - heading "Initial Consultation" [level=3] [ref=e159]
        - paragraph [ref=e160]: We schedule an in-person or online meeting to discuss your trip details, timeline, and specific factory requirements.
      - generic [ref=e162]:
        - generic [ref=e163]: "4"
        - img [ref=e165]
        - heading "Confirm Your Trip" [level=3] [ref=e167]
        - paragraph [ref=e168]: Once you're ready, we arrange flights, accommodation, transport, and your full itinerary in China.
      - generic [ref=e170]:
        - generic [ref=e171]: "5"
        - img [ref=e173]
        - heading "Factory Visit Experience" [level=3] [ref=e177]
        - paragraph [ref=e178]: Arrive in China — your bilingual guide accompanies you throughout. Visit factories, ask questions, and make informed decisions.
    - generic [ref=e179]:
      - link "View All Services" [ref=e180] [cursor=pointer]:
        - /url: /services
        - text: View All Services
        - img [ref=e181]
      - link "Industries We Cover" [ref=e183] [cursor=pointer]:
        - /url: "#industries"
        - generic [ref=e184]: Industries We Cover
        - img [ref=e185]
  - generic [ref=e188]:
    - generic [ref=e189]:
      - paragraph [ref=e190]: Factory Directory
      - heading "Explore Verified Manufacturers" [level=2] [ref=e191]
    - generic [ref=e193]:
      - button "All" [ref=e194] [cursor=pointer]
      - button "Electronics" [ref=e195] [cursor=pointer]
      - button "Furniture" [ref=e196] [cursor=pointer]
      - button "Robotics" [ref=e197] [cursor=pointer]
      - button "EV Battery" [ref=e198] [cursor=pointer]
      - button "CBD Property" [ref=e199] [cursor=pointer]
      - button "Construction" [ref=e200] [cursor=pointer]
      - button "Food & Beverage" [ref=e201] [cursor=pointer]
    - generic [ref=e203]:
      - generic [ref=e206]:
        - generic [ref=e207] [cursor=pointer]:
          - generic [ref=e208]:
            - heading "Foshan" [level=3] [ref=e209]
            - generic [ref=e210]: Guangdong
          - paragraph [ref=e211]: 80 factories
          - paragraph [ref=e212]: Furniture manufacturing hub
        - generic [ref=e213] [cursor=pointer]:
          - generic [ref=e214]:
            - heading "Dongguan" [level=3] [ref=e215]
            - generic [ref=e216]: Guangdong
          - paragraph [ref=e217]: 50 factories
          - paragraph [ref=e218]: Electronics manufacturing center
        - generic [ref=e219] [cursor=pointer]:
          - generic [ref=e220]:
            - heading "Hangzhou" [level=3] [ref=e221]
            - generic [ref=e222]: Zhejiang
          - paragraph [ref=e223]: 35 factories
          - paragraph [ref=e224]: E-commerce and tech hub
        - generic [ref=e225] [cursor=pointer]:
          - generic [ref=e226]:
            - heading "Guangzhou" [level=3] [ref=e227]
            - generic [ref=e228]: Guangdong
          - paragraph [ref=e229]: 60 factories
          - paragraph [ref=e230]: Trading and export hub
        - generic [ref=e231] [cursor=pointer]:
          - generic [ref=e232]:
            - heading "Shenzhen" [level=3] [ref=e233]
            - generic [ref=e234]: Guangdong
          - paragraph [ref=e235]: 75 factories
          - paragraph [ref=e236]: Global tech innovation center
        - generic [ref=e237] [cursor=pointer]:
          - generic [ref=e238]:
            - heading "Suzhou" [level=3] [ref=e239]
            - generic [ref=e240]: Jiangsu
          - paragraph [ref=e241]: 40 factories
          - paragraph [ref=e242]: High-tech industrial park
        - generic [ref=e243] [cursor=pointer]:
          - generic [ref=e244]:
            - heading "Shanghai" [level=3] [ref=e245]
            - generic [ref=e246]: Shanghai
          - paragraph [ref=e247]: 55 factories
          - paragraph [ref=e248]: International trade gateway
        - generic [ref=e249] [cursor=pointer]:
          - generic [ref=e250]:
            - heading "Chengdu" [level=3] [ref=e251]
            - generic [ref=e252]: Sichuan
          - paragraph [ref=e253]: 25 factories
          - paragraph [ref=e254]: Western China logistics hub
        - generic [ref=e255] [cursor=pointer]:
          - generic [ref=e256]:
            - heading "Beijing" [level=3] [ref=e257]
            - generic [ref=e258]: Beijing
          - paragraph [ref=e259]: 30 factories
          - paragraph [ref=e260]: Capital business district
        - generic [ref=e261] [cursor=pointer]:
          - generic [ref=e262]:
            - heading "Wuhan" [level=3] [ref=e263]
            - generic [ref=e264]: Hubei
          - paragraph [ref=e265]: 20 factories
          - paragraph [ref=e266]: Central China transport hub
      - generic [ref=e268]:
        - generic:
          - generic:
            - button:
              - img [ref=e270] [cursor=pointer]
            - button:
              - img [ref=e274] [cursor=pointer]
            - button:
              - img [ref=e278] [cursor=pointer]
            - button:
              - img [ref=e282] [cursor=pointer]
            - button:
              - img [ref=e286] [cursor=pointer]
            - button:
              - img [ref=e290] [cursor=pointer]
            - button:
              - img [ref=e294] [cursor=pointer]
            - button:
              - img [ref=e298] [cursor=pointer]
            - button:
              - img [ref=e302] [cursor=pointer]
            - button:
              - img [ref=e306] [cursor=pointer]
            - button:
              - img [ref=e310] [cursor=pointer]
            - button:
              - img [ref=e314] [cursor=pointer]
            - button:
              - img [ref=e318] [cursor=pointer]
            - button:
              - img [ref=e322] [cursor=pointer]
            - button:
              - img [ref=e326] [cursor=pointer]
            - button:
              - img [ref=e330] [cursor=pointer]
            - button:
              - img [ref=e334] [cursor=pointer]
            - button:
              - img [ref=e338] [cursor=pointer]
            - button:
              - img [ref=e342] [cursor=pointer]
            - button:
              - img [ref=e346] [cursor=pointer]
            - button:
              - img [ref=e350] [cursor=pointer]
            - button:
              - img [ref=e354] [cursor=pointer]
            - button:
              - img [ref=e358] [cursor=pointer]
            - button:
              - img [ref=e362] [cursor=pointer]
            - button:
              - img [ref=e366] [cursor=pointer]
            - button:
              - img [ref=e370] [cursor=pointer]
            - button:
              - img [ref=e374] [cursor=pointer]
            - button:
              - img [ref=e378] [cursor=pointer]
            - button:
              - img [ref=e382] [cursor=pointer]
            - button:
              - img [ref=e386] [cursor=pointer]
            - button:
              - img [ref=e390] [cursor=pointer]
            - button:
              - img [ref=e394] [cursor=pointer]
            - button:
              - img [ref=e398] [cursor=pointer]
            - button:
              - img [ref=e402] [cursor=pointer]
            - button:
              - img [ref=e406] [cursor=pointer]
            - button:
              - img [ref=e410] [cursor=pointer]
            - button:
              - img [ref=e414] [cursor=pointer]
            - button:
              - img [ref=e418] [cursor=pointer]
            - button:
              - img [ref=e422] [cursor=pointer]
            - button:
              - img [ref=e426] [cursor=pointer]
            - button:
              - img [ref=e430] [cursor=pointer]
            - button:
              - img [ref=e434] [cursor=pointer]
            - button:
              - img [ref=e438] [cursor=pointer]
            - button:
              - img [ref=e442] [cursor=pointer]
            - button:
              - img [ref=e446] [cursor=pointer]
            - button:
              - img [ref=e450] [cursor=pointer]
            - button:
              - img [ref=e454] [cursor=pointer]
            - button:
              - img [ref=e458] [cursor=pointer]
            - button:
              - img [ref=e462] [cursor=pointer]
            - button:
              - img [ref=e466] [cursor=pointer]
            - button:
              - img [ref=e470] [cursor=pointer]
            - button:
              - img [ref=e474] [cursor=pointer]
            - button:
              - img [ref=e478] [cursor=pointer]
            - button:
              - img [ref=e482] [cursor=pointer]
            - button:
              - img [ref=e486] [cursor=pointer]
            - button:
              - img [ref=e490] [cursor=pointer]
            - button:
              - img [ref=e494] [cursor=pointer]
            - button:
              - img [ref=e498] [cursor=pointer]
            - button:
              - img [ref=e502] [cursor=pointer]
            - button:
              - img [ref=e506] [cursor=pointer]
            - button:
              - img [ref=e510] [cursor=pointer]
            - button:
              - img [ref=e514] [cursor=pointer]
            - button:
              - img [ref=e518] [cursor=pointer]
            - button:
              - img [ref=e522] [cursor=pointer]
            - button:
              - img [ref=e526] [cursor=pointer]
            - button:
              - img [ref=e530] [cursor=pointer]
            - button:
              - img [ref=e534] [cursor=pointer]
            - button:
              - img [ref=e538] [cursor=pointer]
            - button:
              - img [ref=e542] [cursor=pointer]
            - button:
              - img [ref=e546] [cursor=pointer]
            - button:
              - img [ref=e550] [cursor=pointer]
            - button:
              - img [ref=e554] [cursor=pointer]
            - button:
              - img [ref=e558] [cursor=pointer]
            - button:
              - img [ref=e562] [cursor=pointer]
            - button:
              - img [ref=e566] [cursor=pointer]
            - button:
              - img [ref=e570] [cursor=pointer]
            - button:
              - img [ref=e574] [cursor=pointer]
            - button:
              - img [ref=e578] [cursor=pointer]
            - button:
              - img [ref=e582] [cursor=pointer]
            - button:
              - img [ref=e586] [cursor=pointer]
            - button:
              - img [ref=e590] [cursor=pointer]
            - button:
              - img [ref=e594] [cursor=pointer]
            - button:
              - img [ref=e598] [cursor=pointer]
            - button:
              - img [ref=e602] [cursor=pointer]
            - button:
              - img [ref=e606] [cursor=pointer]
            - button:
              - img [ref=e610] [cursor=pointer]
            - button:
              - img [ref=e614] [cursor=pointer]
            - button:
              - img [ref=e618] [cursor=pointer]
            - button:
              - img [ref=e622] [cursor=pointer]
            - button:
              - img [ref=e626] [cursor=pointer]
            - button:
              - img [ref=e630] [cursor=pointer]
            - button:
              - img [ref=e634] [cursor=pointer]
            - button:
              - img [ref=e638] [cursor=pointer]
            - button:
              - img [ref=e642] [cursor=pointer]
            - button:
              - img [ref=e646] [cursor=pointer]
            - button:
              - img [ref=e650] [cursor=pointer]
            - button:
              - img [ref=e654] [cursor=pointer]
            - button:
              - img [ref=e658] [cursor=pointer]
            - button:
              - img [ref=e662] [cursor=pointer]
            - button:
              - img [ref=e666] [cursor=pointer]
            - button:
              - img [ref=e670] [cursor=pointer]
            - button:
              - img [ref=e674] [cursor=pointer]
            - button:
              - img [ref=e678] [cursor=pointer]
            - button:
              - img [ref=e682] [cursor=pointer]
            - button:
              - img [ref=e686] [cursor=pointer]
            - button:
              - img [ref=e690] [cursor=pointer]
            - button:
              - img [ref=e694] [cursor=pointer]
            - button:
              - img [ref=e698] [cursor=pointer]
            - button:
              - img [ref=e702] [cursor=pointer]
            - button:
              - img [ref=e706] [cursor=pointer]
            - button:
              - img [ref=e710] [cursor=pointer]
            - button:
              - img [ref=e714] [cursor=pointer]
            - button:
              - img [ref=e718] [cursor=pointer]
            - button:
              - img [ref=e722] [cursor=pointer]
            - button:
              - img [ref=e726] [cursor=pointer]
            - button:
              - img [ref=e730] [cursor=pointer]
            - button:
              - img [ref=e734] [cursor=pointer]
            - button:
              - img [ref=e738] [cursor=pointer]
            - button:
              - img [ref=e742] [cursor=pointer]
            - button:
              - img [ref=e746] [cursor=pointer]
            - button:
              - img [ref=e750] [cursor=pointer]
            - button:
              - img [ref=e754] [cursor=pointer]
            - button:
              - img [ref=e758] [cursor=pointer]
            - button:
              - img [ref=e762] [cursor=pointer]
            - button:
              - img [ref=e766] [cursor=pointer]
            - button:
              - img [ref=e770] [cursor=pointer]
            - button:
              - img [ref=e774] [cursor=pointer]
            - button:
              - img [ref=e778] [cursor=pointer]
            - button:
              - img [ref=e782] [cursor=pointer]
            - button:
              - img [ref=e786] [cursor=pointer]
            - button:
              - img [ref=e790] [cursor=pointer]
            - button:
              - img [ref=e794] [cursor=pointer]
            - button:
              - img [ref=e798] [cursor=pointer]
            - button:
              - img [ref=e802] [cursor=pointer]
            - button:
              - img [ref=e806] [cursor=pointer]
            - button:
              - img [ref=e810] [cursor=pointer]
            - button:
              - img [ref=e814] [cursor=pointer]
            - button:
              - img [ref=e818] [cursor=pointer]
            - button:
              - img [ref=e822] [cursor=pointer]
            - button:
              - img [ref=e826] [cursor=pointer]
            - button:
              - img [ref=e830] [cursor=pointer]
            - button:
              - img [ref=e834] [cursor=pointer]
            - button:
              - img [ref=e838] [cursor=pointer]
            - button:
              - img [ref=e842] [cursor=pointer]
            - button:
              - img [ref=e846] [cursor=pointer]
            - button:
              - img [ref=e850] [cursor=pointer]
            - button:
              - img [ref=e854] [cursor=pointer]
            - button:
              - img [ref=e858] [cursor=pointer]
            - button:
              - img [ref=e862] [cursor=pointer]
            - button:
              - img [ref=e866] [cursor=pointer]
            - button:
              - img [ref=e870] [cursor=pointer]
            - button:
              - img [ref=e874] [cursor=pointer]
            - button:
              - img [ref=e878] [cursor=pointer]
            - button:
              - img [ref=e882] [cursor=pointer]
            - button:
              - img [ref=e886] [cursor=pointer]
            - button:
              - img [ref=e890] [cursor=pointer]
            - button:
              - img [ref=e894] [cursor=pointer]
            - button:
              - img [ref=e898] [cursor=pointer]
            - button:
              - img [ref=e902] [cursor=pointer]
            - button:
              - img [ref=e906] [cursor=pointer]
            - button:
              - img [ref=e910] [cursor=pointer]
            - button:
              - img [ref=e914] [cursor=pointer]
            - button:
              - img [ref=e918] [cursor=pointer]
            - button:
              - img [ref=e922] [cursor=pointer]
            - button:
              - img [ref=e926] [cursor=pointer]
            - button:
              - img [ref=e930] [cursor=pointer]
            - button:
              - img [ref=e934] [cursor=pointer]
            - button:
              - img [ref=e938] [cursor=pointer]
            - button:
              - img [ref=e942] [cursor=pointer]
            - button:
              - img [ref=e946] [cursor=pointer]
            - button:
              - img [ref=e950] [cursor=pointer]
            - button:
              - img [ref=e954] [cursor=pointer]
            - button:
              - img [ref=e958] [cursor=pointer]
            - button:
              - img [ref=e962] [cursor=pointer]
            - button:
              - img [ref=e966] [cursor=pointer]
            - button:
              - img [ref=e970] [cursor=pointer]
            - button:
              - img [ref=e974] [cursor=pointer]
            - button:
              - img [ref=e978] [cursor=pointer]
            - button:
              - img [ref=e982] [cursor=pointer]
            - button:
              - img [ref=e986] [cursor=pointer]
            - button:
              - img [ref=e990] [cursor=pointer]
            - button:
              - img [ref=e994] [cursor=pointer]
            - button:
              - img [ref=e998] [cursor=pointer]
            - button:
              - img [ref=e1002] [cursor=pointer]
            - button:
              - img [ref=e1006] [cursor=pointer]
            - button:
              - img [ref=e1010] [cursor=pointer]
            - button:
              - img [ref=e1014] [cursor=pointer]
            - button:
              - img [ref=e1018] [cursor=pointer]
            - button:
              - img [ref=e1022] [cursor=pointer]
            - button:
              - img [ref=e1026] [cursor=pointer]
            - button:
              - img [ref=e1030] [cursor=pointer]
            - button:
              - img [ref=e1034] [cursor=pointer]
            - button:
              - img [ref=e1038] [cursor=pointer]
            - button:
              - img [ref=e1042] [cursor=pointer]
            - button:
              - img [ref=e1046] [cursor=pointer]
            - button:
              - img [ref=e1050] [cursor=pointer]
            - button:
              - img [ref=e1054] [cursor=pointer]
            - button:
              - img [ref=e1058] [cursor=pointer]
            - button:
              - img [ref=e1062] [cursor=pointer]
            - button:
              - img [ref=e1066] [cursor=pointer]
            - button:
              - img [ref=e1070] [cursor=pointer]
            - button:
              - img [ref=e1074] [cursor=pointer]
            - button:
              - img [ref=e1078] [cursor=pointer]
            - button:
              - img [ref=e1082] [cursor=pointer]
            - button:
              - img [ref=e1086] [cursor=pointer]
            - button:
              - img [ref=e1090] [cursor=pointer]
            - button:
              - img [ref=e1094] [cursor=pointer]
            - button:
              - img [ref=e1098] [cursor=pointer]
            - button:
              - img [ref=e1102] [cursor=pointer]
            - button:
              - img [ref=e1106] [cursor=pointer]
            - button:
              - img [ref=e1110] [cursor=pointer]
            - button:
              - img [ref=e1114] [cursor=pointer]
            - button:
              - img [ref=e1118] [cursor=pointer]
            - button:
              - img [ref=e1122] [cursor=pointer]
            - button:
              - img [ref=e1126] [cursor=pointer]
            - button:
              - img [ref=e1130] [cursor=pointer]
            - button:
              - img [ref=e1134] [cursor=pointer]
            - button:
              - img [ref=e1138] [cursor=pointer]
            - button:
              - img [ref=e1142] [cursor=pointer]
            - button:
              - img [ref=e1146] [cursor=pointer]
            - button:
              - img [ref=e1150] [cursor=pointer]
            - button:
              - img [ref=e1154] [cursor=pointer]
            - button:
              - img [ref=e1158] [cursor=pointer]
            - button:
              - img [ref=e1162] [cursor=pointer]
            - button:
              - img [ref=e1166] [cursor=pointer]
            - button:
              - img [ref=e1170] [cursor=pointer]
            - button:
              - img [ref=e1174] [cursor=pointer]
            - button:
              - img [ref=e1178] [cursor=pointer]
            - button:
              - img [ref=e1182] [cursor=pointer]
            - button:
              - img [ref=e1186] [cursor=pointer]
            - button:
              - img [ref=e1190] [cursor=pointer]
            - button:
              - img [ref=e1194] [cursor=pointer]
            - button:
              - img [ref=e1198] [cursor=pointer]
            - button:
              - img [ref=e1202] [cursor=pointer]
            - button:
              - img [ref=e1206] [cursor=pointer]
            - button:
              - img [ref=e1210] [cursor=pointer]
            - button:
              - img [ref=e1214] [cursor=pointer]
            - button:
              - img [ref=e1218] [cursor=pointer]
            - button:
              - img [ref=e1222] [cursor=pointer]
            - button:
              - img [ref=e1226] [cursor=pointer]
            - button:
              - img [ref=e1230] [cursor=pointer]
            - button:
              - img [ref=e1234] [cursor=pointer]
            - button:
              - img [ref=e1238] [cursor=pointer]
            - button:
              - img [ref=e1242] [cursor=pointer]
            - button:
              - img [ref=e1246] [cursor=pointer]
            - button:
              - img [ref=e1250] [cursor=pointer]
            - button:
              - img [ref=e1254] [cursor=pointer]
            - button:
              - img [ref=e1258] [cursor=pointer]
            - button:
              - img [ref=e1262] [cursor=pointer]
            - button:
              - img [ref=e1266] [cursor=pointer]
            - button:
              - img [ref=e1270] [cursor=pointer]
            - button:
              - img [ref=e1274] [cursor=pointer]
            - button:
              - img [ref=e1278] [cursor=pointer]
            - button:
              - img [ref=e1282] [cursor=pointer]
            - button:
              - img [ref=e1286] [cursor=pointer]
            - button:
              - img [ref=e1290] [cursor=pointer]
            - button:
              - img [ref=e1294] [cursor=pointer]
            - button:
              - img [ref=e1298] [cursor=pointer]
            - button:
              - img [ref=e1302] [cursor=pointer]
            - button:
              - img [ref=e1306] [cursor=pointer]
            - button:
              - img [ref=e1310] [cursor=pointer]
            - button:
              - img [ref=e1314] [cursor=pointer]
            - button:
              - img [ref=e1318] [cursor=pointer]
            - button:
              - img [ref=e1322] [cursor=pointer]
            - button:
              - img [ref=e1326] [cursor=pointer]
            - button:
              - img [ref=e1330] [cursor=pointer]
            - button:
              - img [ref=e1334] [cursor=pointer]
            - button:
              - img [ref=e1338] [cursor=pointer]
            - button:
              - img [ref=e1342] [cursor=pointer]
            - button:
              - img [ref=e1346] [cursor=pointer]
            - button:
              - img [ref=e1350] [cursor=pointer]
            - button:
              - img [ref=e1354] [cursor=pointer]
            - button:
              - img [ref=e1358] [cursor=pointer]
            - button:
              - img [ref=e1362] [cursor=pointer]
            - button:
              - img [ref=e1366] [cursor=pointer]
            - button:
              - img [ref=e1370] [cursor=pointer]
            - button:
              - img [ref=e1374] [cursor=pointer]
            - button:
              - img [ref=e1378] [cursor=pointer]
            - button:
              - img [ref=e1382] [cursor=pointer]
            - button:
              - img [ref=e1386] [cursor=pointer]
            - button:
              - img [ref=e1390] [cursor=pointer]
            - button:
              - img [ref=e1394] [cursor=pointer]
            - button:
              - img [ref=e1398] [cursor=pointer]
            - button:
              - img [ref=e1402] [cursor=pointer]
            - button:
              - img [ref=e1406] [cursor=pointer]
            - button:
              - img [ref=e1410] [cursor=pointer]
            - button:
              - img [ref=e1414] [cursor=pointer]
            - button:
              - img [ref=e1418] [cursor=pointer]
            - button:
              - img [ref=e1422] [cursor=pointer]
            - button:
              - img [ref=e1426] [cursor=pointer]
            - button:
              - img [ref=e1430] [cursor=pointer]
            - button:
              - img [ref=e1434] [cursor=pointer]
            - button:
              - img [ref=e1438] [cursor=pointer]
            - button:
              - img [ref=e1442] [cursor=pointer]
            - button:
              - img [ref=e1446] [cursor=pointer]
            - button:
              - img [ref=e1450] [cursor=pointer]
            - button:
              - img [ref=e1454] [cursor=pointer]
            - button:
              - img [ref=e1458] [cursor=pointer]
            - button:
              - img [ref=e1462] [cursor=pointer]
            - button:
              - img [ref=e1466] [cursor=pointer]
            - button:
              - img [ref=e1470] [cursor=pointer]
            - button:
              - img [ref=e1474] [cursor=pointer]
            - button:
              - img [ref=e1478] [cursor=pointer]
            - button:
              - img [ref=e1482] [cursor=pointer]
            - button:
              - img [ref=e1486] [cursor=pointer]
            - button:
              - img [ref=e1490] [cursor=pointer]
            - button:
              - img [ref=e1494] [cursor=pointer]
            - button:
              - img [ref=e1498] [cursor=pointer]
            - button:
              - img [ref=e1502] [cursor=pointer]
            - button:
              - img [ref=e1506] [cursor=pointer]
            - button:
              - img [ref=e1510] [cursor=pointer]
            - button:
              - img [ref=e1514] [cursor=pointer]
            - button:
              - img [ref=e1518] [cursor=pointer]
            - button:
              - img [ref=e1522] [cursor=pointer]
            - button:
              - img [ref=e1526] [cursor=pointer]
            - button:
              - img [ref=e1530] [cursor=pointer]
            - button:
              - img [ref=e1534] [cursor=pointer]
            - button:
              - img [ref=e1538] [cursor=pointer]
            - button:
              - img [ref=e1542] [cursor=pointer]
            - button:
              - img [ref=e1546] [cursor=pointer]
            - button:
              - img [ref=e1550] [cursor=pointer]
            - button:
              - img [ref=e1554] [cursor=pointer]
            - button:
              - img [ref=e1558] [cursor=pointer]
            - button:
              - img [ref=e1562] [cursor=pointer]
            - button:
              - img [ref=e1566] [cursor=pointer]
            - button:
              - img [ref=e1570] [cursor=pointer]
            - button:
              - img [ref=e1574] [cursor=pointer]
            - button:
              - img [ref=e1578] [cursor=pointer]
            - button:
              - img [ref=e1582] [cursor=pointer]
            - button:
              - img [ref=e1586] [cursor=pointer]
            - button:
              - img [ref=e1590] [cursor=pointer]
            - button:
              - img [ref=e1594] [cursor=pointer]
            - button:
              - img [ref=e1598] [cursor=pointer]
            - button:
              - img [ref=e1602] [cursor=pointer]
            - button:
              - img [ref=e1606] [cursor=pointer]
            - button:
              - img [ref=e1610] [cursor=pointer]
            - button:
              - img [ref=e1614] [cursor=pointer]
            - button:
              - img [ref=e1618] [cursor=pointer]
            - button:
              - img [ref=e1622] [cursor=pointer]
            - button:
              - img [ref=e1626] [cursor=pointer]
            - button:
              - img [ref=e1630] [cursor=pointer]
            - button:
              - img [ref=e1634] [cursor=pointer]
            - button:
              - img [ref=e1638] [cursor=pointer]
            - button:
              - img [ref=e1642] [cursor=pointer]
            - button:
              - img [ref=e1646] [cursor=pointer]
            - button:
              - img [ref=e1650] [cursor=pointer]
            - button:
              - img [ref=e1654] [cursor=pointer]
            - button:
              - img [ref=e1658] [cursor=pointer]
            - button:
              - img [ref=e1662] [cursor=pointer]
            - button:
              - img [ref=e1666] [cursor=pointer]
            - button:
              - img [ref=e1670] [cursor=pointer]
            - button:
              - img [ref=e1674] [cursor=pointer]
            - button:
              - img [ref=e1678] [cursor=pointer]
            - button:
              - img [ref=e1682] [cursor=pointer]
            - button:
              - img [ref=e1686] [cursor=pointer]
            - button:
              - img [ref=e1690] [cursor=pointer]
            - button:
              - img [ref=e1694] [cursor=pointer]
            - button:
              - img [ref=e1698] [cursor=pointer]
            - button:
              - img [ref=e1702] [cursor=pointer]
            - button:
              - img [ref=e1706] [cursor=pointer]
            - button:
              - img [ref=e1710] [cursor=pointer]
            - button:
              - img [ref=e1714] [cursor=pointer]
            - button:
              - img [ref=e1718] [cursor=pointer]
            - button:
              - img [ref=e1722] [cursor=pointer]
            - button:
              - img [ref=e1726] [cursor=pointer]
            - button:
              - img [ref=e1730] [cursor=pointer]
            - button:
              - img [ref=e1734] [cursor=pointer]
            - button:
              - img [ref=e1738] [cursor=pointer]
            - button:
              - img [ref=e1742] [cursor=pointer]
            - button:
              - img [ref=e1746] [cursor=pointer]
            - button:
              - img [ref=e1750] [cursor=pointer]
            - button:
              - img [ref=e1754] [cursor=pointer]
            - button:
              - img [ref=e1758] [cursor=pointer]
            - button:
              - img [ref=e1762] [cursor=pointer]
            - button:
              - img [ref=e1766] [cursor=pointer]
            - button:
              - img [ref=e1770] [cursor=pointer]
            - button:
              - img [ref=e1774] [cursor=pointer]
            - button:
              - img [ref=e1778] [cursor=pointer]
            - button:
              - img [ref=e1782] [cursor=pointer]
            - button:
              - img [ref=e1786] [cursor=pointer]
            - button:
              - img [ref=e1790] [cursor=pointer]
            - button:
              - img [ref=e1794] [cursor=pointer]
            - button:
              - img [ref=e1798] [cursor=pointer]
            - button:
              - img [ref=e1802] [cursor=pointer]
            - button:
              - img [ref=e1806] [cursor=pointer]
            - button:
              - img [ref=e1810] [cursor=pointer]
            - button:
              - img [ref=e1814] [cursor=pointer]
            - button:
              - img [ref=e1818] [cursor=pointer]
            - button:
              - img [ref=e1822] [cursor=pointer]
            - button:
              - img [ref=e1826] [cursor=pointer]
            - button:
              - img [ref=e1830] [cursor=pointer]
            - button:
              - img [ref=e1834] [cursor=pointer]
            - button:
              - img [ref=e1838] [cursor=pointer]
            - button:
              - img [ref=e1842] [cursor=pointer]
            - button:
              - img [ref=e1846] [cursor=pointer]
            - button:
              - img [ref=e1850] [cursor=pointer]
            - button:
              - img [ref=e1854] [cursor=pointer]
            - button:
              - img [ref=e1858] [cursor=pointer]
            - button:
              - img [ref=e1862] [cursor=pointer]
            - button:
              - img [ref=e1866] [cursor=pointer]
            - button:
              - img [ref=e1870] [cursor=pointer]
            - button:
              - img [ref=e1874] [cursor=pointer]
            - button:
              - img [ref=e1878] [cursor=pointer]
            - button:
              - img [ref=e1882] [cursor=pointer]
            - button:
              - img [ref=e1886] [cursor=pointer]
            - button:
              - img [ref=e1890] [cursor=pointer]
            - button:
              - img [ref=e1894] [cursor=pointer]
            - button:
              - img [ref=e1898] [cursor=pointer]
            - button:
              - img [ref=e1902] [cursor=pointer]
            - button:
              - img [ref=e1906] [cursor=pointer]
            - button:
              - img [ref=e1910] [cursor=pointer]
            - button:
              - img [ref=e1914] [cursor=pointer]
            - button:
              - img [ref=e1918] [cursor=pointer]
            - button:
              - img [ref=e1922] [cursor=pointer]
            - button:
              - img [ref=e1926] [cursor=pointer]
            - button:
              - img [ref=e1930] [cursor=pointer]
            - button:
              - img [ref=e1934] [cursor=pointer]
            - button:
              - img [ref=e1938] [cursor=pointer]
            - button:
              - img [ref=e1942] [cursor=pointer]
            - button:
              - img [ref=e1946] [cursor=pointer]
            - button:
              - img [ref=e1950] [cursor=pointer]
            - button:
              - img [ref=e1954] [cursor=pointer]
            - button:
              - img [ref=e1958] [cursor=pointer]
            - button:
              - img [ref=e1962] [cursor=pointer]
            - button:
              - img [ref=e1966] [cursor=pointer]
            - button:
              - img [ref=e1970] [cursor=pointer]
            - button:
              - img [ref=e1974] [cursor=pointer]
            - button:
              - img [ref=e1978] [cursor=pointer]
            - button:
              - img [ref=e1982] [cursor=pointer]
            - button:
              - img [ref=e1986] [cursor=pointer]
            - button:
              - img [ref=e1990] [cursor=pointer]
            - button:
              - img [ref=e1994] [cursor=pointer]
            - button:
              - img [ref=e1998] [cursor=pointer]
            - button:
              - img [ref=e2002] [cursor=pointer]
            - button:
              - img [ref=e2006] [cursor=pointer]
            - button:
              - img [ref=e2010] [cursor=pointer]
            - button:
              - img [ref=e2014] [cursor=pointer]
            - button:
              - img [ref=e2018] [cursor=pointer]
            - button:
              - img [ref=e2022] [cursor=pointer]
            - button:
              - img [ref=e2026] [cursor=pointer]
            - button:
              - img [ref=e2030] [cursor=pointer]
            - button:
              - img [ref=e2034] [cursor=pointer]
            - button:
              - img [ref=e2038] [cursor=pointer]
            - button:
              - img [ref=e2042] [cursor=pointer]
            - button:
              - img [ref=e2046] [cursor=pointer]
            - button:
              - img [ref=e2050] [cursor=pointer]
            - button:
              - img [ref=e2054] [cursor=pointer]
            - button:
              - img [ref=e2058] [cursor=pointer]
            - button:
              - img [ref=e2062] [cursor=pointer]
            - button:
              - img [ref=e2066] [cursor=pointer]
            - button:
              - img [ref=e2070] [cursor=pointer]
            - button:
              - img [ref=e2074] [cursor=pointer]
            - button:
              - img [ref=e2078] [cursor=pointer]
            - button:
              - img [ref=e2082] [cursor=pointer]
            - button:
              - img [ref=e2086] [cursor=pointer]
            - button:
              - img [ref=e2090] [cursor=pointer]
            - button:
              - img [ref=e2094] [cursor=pointer]
            - button:
              - img [ref=e2098] [cursor=pointer]
            - button:
              - img [ref=e2102] [cursor=pointer]
            - button:
              - img [ref=e2106] [cursor=pointer]
            - button:
              - img [ref=e2110] [cursor=pointer]
            - button:
              - img [ref=e2114] [cursor=pointer]
            - button:
              - img [ref=e2118] [cursor=pointer]
            - button:
              - img [ref=e2122] [cursor=pointer]
            - button:
              - img [ref=e2126] [cursor=pointer]
            - button:
              - img [ref=e2130] [cursor=pointer]
            - button:
              - img [ref=e2134] [cursor=pointer]
            - button:
              - img [ref=e2138] [cursor=pointer]
            - button:
              - img [ref=e2142] [cursor=pointer]
            - button:
              - img [ref=e2146] [cursor=pointer]
        - generic [ref=e2149]:
          - button "Zoom in" [ref=e2150] [cursor=pointer]: +
          - button "Zoom out" [ref=e2151] [cursor=pointer]: −
    - link "View Full Directory" [ref=e2153] [cursor=pointer]:
      - /url: /enquiry
      - text: View Full Directory
      - img [ref=e2154]
  - generic [ref=e2157]:
    - paragraph [ref=e2158]: Frequently Asked Questions
    - heading "Everything You Need to Know" [level=2] [ref=e2159]
    - generic [ref=e2160]:
      - button "What is a China sourcing agent in Australia and why do I need one? +" [ref=e2162] [cursor=pointer]:
        - generic [ref=e2163]: What is a China sourcing agent in Australia and why do I need one?
        - generic [ref=e2164]: +
      - button "How do I visit Chinese factories safely as an Australian business? +" [ref=e2166] [cursor=pointer]:
        - generic [ref=e2167]: How do I visit Chinese factories safely as an Australian business?
        - generic [ref=e2168]: +
      - button "What does a China sourcing tour include? +" [ref=e2170] [cursor=pointer]:
        - generic [ref=e2171]: What does a China sourcing tour include?
        - generic [ref=e2172]: +
      - button "What are China business tours and how do they work for Australian importers? +" [ref=e2174] [cursor=pointer]:
        - generic [ref=e2175]: What are China business tours and how do they work for Australian importers?
        - generic [ref=e2176]: +
      - button "How can Australian businesses find reliable Chinese wholesalers? +" [ref=e2178] [cursor=pointer]:
        - generic [ref=e2179]: How can Australian businesses find reliable Chinese wholesalers?
        - generic [ref=e2180]: +
      - button "What is included in a China business trip package? +" [ref=e2182] [cursor=pointer]:
        - generic [ref=e2183]: What is included in a China business trip package?
        - generic [ref=e2184]: +
      - button "What is included in the service fee? +" [ref=e2186] [cursor=pointer]:
        - generic [ref=e2187]: What is included in the service fee?
        - generic [ref=e2188]: +
      - button "How far in advance do I need to book? +" [ref=e2190] [cursor=pointer]:
        - generic [ref=e2191]: How far in advance do I need to book?
        - generic [ref=e2192]: +
      - button "What if I do not find a suitable supplier? +" [ref=e2194] [cursor=pointer]:
        - generic [ref=e2195]: What if I do not find a suitable supplier?
        - generic [ref=e2196]: +
      - button "Do I need to speak Mandarin? +" [ref=e2198] [cursor=pointer]:
        - generic [ref=e2199]: Do I need to speak Mandarin?
        - generic [ref=e2200]: +
  - generic [ref=e2202]:
    - generic [ref=e2203]:
      - heading "Your Suppliers Are Ready. Are You?" [level=2] [ref=e2204]
      - paragraph [ref=e2205]: Book a free 30-minute discovery call — no obligation, no pressure.
    - generic [ref=e2206]:
      - link "Start Your China Trip →" [ref=e2207] [cursor=pointer]:
        - /url: /enquiry
      - link "See How It Works" [ref=e2208] [cursor=pointer]:
        - /url: /#howitworks
  - contentinfo [ref=e2209]:
    - generic [ref=e2210]:
      - generic [ref=e2211]:
        - generic [ref=e2212]:
          - link "Winning Adventure Global" [ref=e2213] [cursor=pointer]:
            - /url: /
            - img "Winning Adventure Global" [ref=e2214]
          - paragraph [ref=e2215]: Connecting Australian businesses with China's finest manufacturers. Your trusted partner for factory sourcing and business travel.
          - link "Winning Adventure Global on LinkedIn" [ref=e2216] [cursor=pointer]:
            - /url: https://www.linkedin.com/company/winning-adventure-global
            - img [ref=e2217]
            - text: Follow us on LinkedIn
        - generic [ref=e2219]:
          - heading "Services" [level=4] [ref=e2220]
          - list [ref=e2221]:
            - listitem [ref=e2222]:
              - link "Business Discovery Trip" [ref=e2223] [cursor=pointer]:
                - /url: /services
            - listitem [ref=e2224]:
              - link "Procurement Support" [ref=e2225] [cursor=pointer]:
                - /url: /services
            - listitem [ref=e2226]:
              - link "Factory Verification" [ref=e2227] [cursor=pointer]:
                - /url: /services
            - listitem [ref=e2228]:
              - link "Quality Inspection" [ref=e2229] [cursor=pointer]:
                - /url: /services
        - generic [ref=e2230]:
          - heading "Industries" [level=4] [ref=e2231]
          - list [ref=e2232]:
            - listitem [ref=e2233]:
              - link "Drones & Robotics" [ref=e2234] [cursor=pointer]:
                - /url: /#industries
            - listitem [ref=e2235]:
              - link "Beauty & Aesthetics" [ref=e2236] [cursor=pointer]:
                - /url: /#industries
            - listitem [ref=e2237]:
              - link "Chemical & Materials" [ref=e2238] [cursor=pointer]:
                - /url: /#industries
            - listitem [ref=e2239]:
              - link "Fashion & Textiles" [ref=e2240] [cursor=pointer]:
                - /url: /#industries
            - listitem [ref=e2241]:
              - link "AV & Electronics" [ref=e2242] [cursor=pointer]:
                - /url: /#industries
        - generic [ref=e2243]:
          - heading "Company" [level=4] [ref=e2244]
          - list [ref=e2245]:
            - listitem [ref=e2246]:
              - link "About Us" [ref=e2247] [cursor=pointer]:
                - /url: /about
            - listitem [ref=e2248]:
              - link "How It Works" [ref=e2249] [cursor=pointer]:
                - /url: /#howitworks
            - listitem [ref=e2250]:
              - link "Resources" [ref=e2251] [cursor=pointer]:
                - /url: /resources
            - listitem [ref=e2252]:
              - link "Contact Us" [ref=e2253] [cursor=pointer]:
                - /url: /enquiry
          - generic [ref=e2254]:
            - generic [ref=e2255]:
              - paragraph [ref=e2256]: Adelaide Office
              - paragraph [ref=e2257]:
                - text: 5/54 Melbourne St
                - text: North Adelaide SA 5006
            - link "mark@winningadventure.com.au" [ref=e2259] [cursor=pointer]:
              - /url: mailto:mark@winningadventure.com.au
      - generic [ref=e2260]:
        - generic [ref=e2261]: © 2026 Winning Adventure Global. All rights reserved.
        - generic [ref=e2263]: "ABN: 30 659 034 919"
  - alert [ref=e2264]
  - img [ref=e2266] [cursor=pointer]