/**
 * Shared removed-content routing rules.
 * Used by middleware.ts and app/sitemap.ts.
 */

export const GONE_SLUGS = [
  "/case-studies",
  "/adelaide",
  "/perth",
  "/brisbane",
  "/melbourne",
  // Added 2026-07-07 — legacy bare-slug URLs. next.config.js used to 301
  // these to an /article/{slug} page that is itself a BLOG_GONE_SLUGS entry
  // (a dead redirect chain: 301 -> 410). Serving 410 directly removes the
  // pointless hop. The next.config.js rules were removed in the same change.
  "/china-vs-alibaba",
  "/china-supplier-verification",
]

export const BLOG_GONE_SLUGS = [
  // Removed 2026-06-24 — news-jacking / off-topic anchors (SEO audit, prepublish-check GATE A).
  // These pulled near-zero qualified traffic and diluted topical authority. 410 = permanent.
  "2026-australia-federal-budget-china-sourcing-impact",
  "2026-australian-federal-budget-import-duty-changes",
  "gold-precious-metals-china-supply-guide",
  "silver-price-impact-china-manufacturing-cost",
  "iran-war-australia-china-supply-chain",
  "reserve-bank-australia-china-sourcing-costs",
  "thucydides-trap-australia-china-supply-chain",
  "us-export-ban-australian-manufacturers",
  // Removed 2026-06-24 (round 2) — news/event-anchored, off-topic.
  "australia-data-centre-supply-chain",
  "australian-energy-regulator-price-announcement",
  "electric-battery-china",
  "electric-vehicle-australia-supply-chain",
  "australian-house-price-forecast-china-materials",
  "resource-china-vs-alibaba",
  "trump-tariffs-australia-china-sourcing-impact",
  "byd-melbourne-supply-chain",
  "liverpool-vs-brentford",
  "asia-pacific-airline-procurement",
  "australia-capital-gains-tax-sme-finance-guide",
  "target-australia-retail",
  "liverpool-brentford-standings",
  "reconciliation-week-sourcing",
  "wisetech-global-logistics-supply-chain-guide",
  "resource-what-happens-when-verification-is-skipped",
  "albanese-family-trust-tax-2026",
  "furniture-factory-tour",
  "chinese-supplier-quality-not-as-promised",
  "albanese-government-tax-changes-australian-importers",
  "resource-australia-china-sourcing-fraud-case-studies",
  "resource-virtual-factory-audit",
  "visiting-chinese-factories-guide",
  "china-factory-tours-australia",
  "resource-machinery-factory-tour",
  "should-i-pay-deposit-chinese-supplier",
  "australia-china-sourcing-fraud-case-studies",
  "supplier-verification-guide",
  "resource-trump-tariffs-australia-china-sourcing-impact",
  "modern-slavery-act-china-supplier-compliance-2026",
  "resource-modern-slavery-act-china-supplier-compliance-2026",
  "resource-supplier-verification-checklist-china",
  "canberra-best-city-for-evs-ev-china-sourcing-guide",
  "machinery-factory-tour",
  "matildas-merchandise",
  "av-equipment-china-factory-verification-guide",
  "brisbane-china-factory-visits",
  "resource-av-equipment-china-factory-verification-guide",
  "supplier-verification-checklist-china",
  "cosmetics-factory-tour",
  "resource-adelaide-china-factory-visits",
  "what-happens-when-verification-is-skipped",
  "brisbane-weather-emergency-supplies-guide",
  "resource-cosmetics-factory-tour",
  "adelaide-china-factory-visits",
  "carnival-corporation-hospitality-supply-chain-guide",
  "perth-china-factory-visits",
  "resource-brisbane-china-factory-visits",
  "resource-melbourne-china-factory-visits",
  "event-hire-china-factory-verification",
  "melbourne-china-factory-visits",
  "resource-av-equipment-procurement-china",
  "resource-event-hire-china-factory-verification",
  "apparel-factory-tour",
  "calculator-business-equipment-china-sourcing-guide",
  "canton-fair-tour",
  "china-supplier-verification",
  "china-vs-alibaba",
  "cost-of-living-crisis-china-sourcing-strategy-guide",
  "electronics-factory-tour",
  "guangzhou-factory-tour",
  "how-to-verify-chinese-factories-1688",
  "macquarie-bank-trade-finance-china-sourcing-guide",
  "resource-apparel-factory-tour",
  "resource-canton-fair-tour",
  "resource-china-business-sourcing-tour",
  "resource-china-factory-tours-australia",
  "resource-electronics-factory-tour",
  "resource-factory-vs-trading-company-china-guide",
  "resource-guangzhou-factory-tour",
  "resource-perth-china-factory-visits",
  "resource-visiting-chinese-factories-australian-business-checklist",
  "shenzhen-factory-visit",
  "toyota-hilux-gvm-upgrade-australia",
  "virtual-factory-audit",
  "case-study-aesthetics-cosmetics",
  "case-study-fashion-apparel",
  "case-study-food-beverage",
  "case-study-healthcare-medical",
  "case-study-lighting-products",
  "case-study-textiles-home-textiles",

  // ============================================
  // Category D cleanup — 139 irrelevant resource pages (sports/entertainment)
  "dashdot-property-collapse-asset-liquidation-guide",
  "kyle-busch-china-auto-parts-sourcing",
  "adelaide-geelong-afl",
  "afl-scores-afl-merchandise-sourcing-guide",
  "albanese-tax-changes-sourcing",
  "american-music-awards-2026-australian-suppliers",
  "andrew-abdo",
  "argentina-honduras-football",
  "aus-pak-cricket-merchandise",
  "australia-citizenship-surge-2026",
  "australia-cricket-team",
  "australia-property-downturn-building-material-imports",
  "australian-telecom-price-hike-2026",
  "avg-travels-liquidation",
  "avg-travels-liquidation-business-assets-sourcing-guide",
  "backrooms-internet-culture-merchandise-sourcing-guide",
  "bangladesh-australia-cricket",
  "bhp-share-price",
  "billy-slater-nrl",
  "brazil-egypt-football",
  "broncos-titans-nrl",
  "canterbury-bulldogs-nrl",
  "carlton-vs-geelong-afl-merchandise-sourcing-guide",
  "cba-share-price-impact-australian-procurement",
  "champions-league-final-football-merchandise-sourcing-guide",
  "charles-leclerc-f1",
  "chiefs-reds-super-rugby",
  "china-home-sales-drop",
  "collingwood-football-club",
  "commsec",
  "connor-watson-nrl-merchandise",
  "cowboys-dolphins-nrl",
  "cricket-scores-fan-merchandise",
  "cricket-sports-equipment-china-sourcing-guide",
  "croatia-belgium-football-merchandise",
  "damien-hardwick-afl",
  "data-center-boom-supply-chain",
  "dollarama-australia-price-trends",
  "dragons-vs-broncos-nrl-merchandise-sourcing-guide",
  "eid-al-adha-sourcing",
  "eid-mubarak-sourcing",
  "el-nino-food-supply-chain-australia",
  "england-new-zealand-cricket",
  "england-world-cup-2026",
  "england-world-cup-squad-china-merchandise",
  "f1-barcelona-2026",
  "f1-standings-2026",
  "fifa-world-cup-stats",
  "folarin-balogun-football",
  "france-ivory-coast-football",
  "fremantle-geelong-afl",
  "french-open-2026-merchandise",
  "geelong-cats-afl",
  "geelong-gold-coast-afl",
  "gold-coast-brisbane-afl",
  "gout-gout-athletics",
  "herbie-farnworth-nrl",
  "illicit-tobacco-trade",
  "india-afghanistan-cricket",
  "india-england-cricket-merchandise",
  "ipl-2026-cricket-merchandise-china-sourcing-guide",
  "iran-new-zealand-football",
  "jakub-mensik-tennis-merchandise",
  "jalen-brunson-basketball",
  "joao-fonseca-tennis-merchandise",
  "job-seeker-reform-impact",
  "john-farnham-music-merchandise-sourcing-guide",
  "kane-williamson-cricket",
  "kimi-antonelli",
  "knicks-nba-playoffs",
  "knicks-spurs-basketball",
  "kumanjayi-white-investment",
  "lachie-neale-afl",
  "laurie-daley-nrl-memorabilia-sourcing-guide",
  "liddell-power-station-manufacturing-energy",
  "lorenzo-musetti-tennis",
  "maja-chwalinska-tennis",
  "marta-kostyuk-tennis-merchandise",
  "melbourne-stars-bbl-merchandise",
  "melbourne-vs-gws-giants-afl-merchandise-sourcing-guide",
  "mirra-andreeva-tennis",
  "mitchell-moses-nrl",
  "modern-warfare-4-gaming-merchandise-china-sourcing-guide",
  "monaco-grand-prix-f1-motorsport-merchandise-sourcing-guide",
  "nba-basketball-merchandise-china-sourcing-guide",
  "nba-finals-2026-merchandise",
  "neale-daniher-death",
  "negative-gearing-properties",
  "nestory-irankunda-football",
  "netherlands-japan-football",
  "new-south-wales-blues-nrl-merchandise-sourcing-guide",
  "nick-cotric-nrl",
  "palace-vs-rayo-vallecano-football-merchandise-sourcing-guide",
  "panthers-vs-warriors-nrl-merchandise-sourcing-guide",
  "power-outage-melbourne",
  "qantas-project-sunrise-delay",
  "qantas-supply-chain-lessons-australian-smes",
  "rcb-vs-gt-cricket-merchandise-guide",
  "richmond-brisbane-afl",
  "robbie-mortimer-entertainment-merchandise-sourcing-guide",
  "roland-garros-2026-tennis-equipment-sourcing-guide",
  "roland-garros-2026-tennis-sporting-goods-sourcing",
  "rr-vs-gt-ipl-cricket-merchandise-sourcing-guide",
  "rr-vs-srh-ipl-cricket-merchandise-sourcing-guide",
  "sam-walker-nrl-rugby-memorabilia-sourcing-guide",
  "sea-eagles-rabbitohs-nrl",
  "sharks-vs-sea-eagles-2026-nrl-merchandise-sourcing-guide",
  "son-heung-min-football",
  "spain-cape-verde-football",
  "spain-iraq-football",
  "spurs-vs-thunder",
  "spurs-vs-thunder-nba-basketball-merchandise-sourcing-guide",
  "sri-lanka",
  "sri-lanka-west-indies-cricket",
  "st-kilda-vs-hawthorn-afl-merchandise-sourcing-guide",
  "star-wars-mandalorian-grogu-licensed-merchandise-sourcing-guide",
  "state-of-origin-game-2",
  "state-of-origin-sports-merchandise-china-supply-chain",
  "state-of-origin-start-time-sourcing-guide",
  "stateside-sports",
  "supercars-championship-motorsport-merchandise-sourcing-guide",
  "svajda-tennis-merchandise",
  "switzerland-australia-football",
  "sydney-vs-richmond-afl-merchandise-sourcing-guide",
  "tennis-australia",
  "the-backrooms-movie-entertainment-products-sourcing-guide",
  "thunder-vs-spurs-nba-basketball-merchandise-sourcing-guide",
  "thunder-vs-spurs-nba-procurement-guide",
  "tony-modra-afl",
  "toy-story-licensed-merchandise-china-sourcing-guide",
  "ultimate-fighting-championship-mma-fitness-sourcing-guide",
  "west-coast-port-adelaide-afl",
  "west-coast-vs-essendon-afl-merchandise-sourcing-guide",
  "west-ham-united",
  "west-indies-women-vs-pakistan-women-cricket-sourcing-guide",
  "wests-tigers-panthers-nrl",
  "who-won-state-of-origin-2026-nrl-merchandise-sourcing-guide",
  "womens-state-of-origin-2026-nrl-merchandise-sourcing-guide",
  "zverev-tennis-merchandise",

  // ============================================
  // Removed 2026-06-26 — brand-riding articles (full SEO audit).
  // Off-topic vs core China-sourcing service; diluted topical authority.
  // RAV4 also contained a factual error (Toyota Altona plant closed 2017).
  "rav4-supply-chain-automotive-sourcing",
  "byd-company-china-supply-chain-guide",
  "bunnings-wholesale-guide",
  "australian-supermarket-china-sourcing-secrets",

  // ============================================
  // Added 2026-07-07 — previously 301-redirected to the generic /article
  // listing page (soft-404 pattern: technically a redirect, but to a page
  // with no real successor content). Converted to 410 for an accurate
  // "this content is gone" signal instead of implying it moved somewhere.
  "tottenham-hotspur",
  "bunnings-wesfarmers-merger-supply-chain",
  "bbq-galore-retail",
  "australian-retail-trends-grilld-coles",
  "kmart-home-retail",
  "bhp",
  "droneshield",
  "reneweconomy",
  "fitbit-air-sourcing",
  "oura-ring-5-wearable-tech-china-sourcing-guide",
  "007-first-light-sourcing",
  "adam-walton-policy-australian-businesses",
  "australian-business-bankruptcy-2026",
  "road-safety-australia-freight-operations",
  "australia-mining-capital-gains-tax-importers",
  "extreme-weather-supply-chain-risk",
  "kenya-sourcing-destination",
  "dubai-international-airport-australia-china-freight",

  // Added 2026-07-07 — next.config.js redirected these to a destination
  // that is itself a BLOG_GONE_SLUGS entry (dead redirect chain: 301 ->
  // 410). Adding the source slug here + removing the next.config.js rule
  // collapses it to a single direct 410.
  "byd-company-supply-chain-guide",
  "electric-battery-supply-chain-china-sourcing-guide",
]

export const BLOG_REDIRECT_TARGETS: Record<string, string> = {
  // Duplicate of the real /services page — 301 to consolidate (2026-06-26 SEO audit).
  "services-wag": "/services",
  "resource-how-to-verify-chinese-factories-1688": "/article/verify-chinese-supplier",
  "resource-shenzhen-factory-visit": "/article/china-factory-tour-guide",
  "resource-should-i-pay-deposit-chinese-supplier": "/article/how-to-negotiate-chinese-factory-guide",
  "resource-chinese-supplier-quality-not-as-promised": "/article/china-sourcing-risks",
}

const BLOG_GONE_SET = new Set(BLOG_GONE_SLUGS)

export function isBlogGoneSlug(slug: string): boolean {
  return BLOG_GONE_SET.has(slug)
}

export function getBlogRedirectTarget(slug: string): string | undefined {
  return BLOG_REDIRECT_TARGETS[slug]
}

export function isGonePath(pathname: string): boolean {
  for (const gonePath of GONE_SLUGS) {
    if (pathname === gonePath || pathname.startsWith(gonePath + "/")) return true
  }
  return false
}
